sudo: false

language: python

python:
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"

env:
  - TEST_TYPE=
  - TEST_TYPE='-t property'
  - TEST_TYPE='-t unit'

before_install:
  - cp instance/configuration_example.py instance/configuration.py
  - cp instance/status_configuration_example.py instance/status_configuration.py

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python manage.py test $TEST_TYPE
  - python manage.py lint

after_success:
  - codecov
