sudo: false

language: python

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - python orchard.py test
  - python orchard.py lint

after_success:
  - codecov
